name: ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/b.jpg
    - assets/images/fb2.png
    - assets/images/google.png
    - assets/images/ig.png
    - assets/images/g2.png
    - assets/images/rr.jpg
    - assets/fonts/med.eot

  fonts:
    - family: awanzaman
      fonts:
        - asset: assets/fonts/med.eot
